//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDChef.Domain
{
   
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("Purchase")]
    public partial class Purchase : BaseEntity
    {
        [Key]
        public int Id { get; set; }
        public string InvoiecNo { get; set; }
        public string Date { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public ICollection<Employee> Employee { get; set; }
        public ICollection<Supplier> Supplier { get; set; }

    }
}
